In [14]:
import numpy as np

In [15]:
# Make the array `my_array`
nums = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print second row of nums
print(nums)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
# Print all elements of nums that are greater than six
print(nums[nums > 6])

[7 8]


In [17]:
# Double every element of nums
nums_dbl = nums*2
print(nums_dbl)

[[ 2  4  6  8]
 [10 12 14 16]]


In [18]:
# Replace the third column of nums
nums[:,2] = nums[:,2] + 1
print(nums)

[[1 2 4 4]
 [5 6 8 8]]
